# Stage 1
FROM node:13 as node_angular_build
WORKDIR /usr/src/app
COPY ./package*.json ./
RUN npm install
COPY . .
RUN npm run build-prod

# Stage 2
FROM nginx:1.13.12-alpine
COPY --from=node_angular_build /usr/src/app/dist/Frontend /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
